---
- name: "Copy configuration files of extension {{ zabbix_extension.name }}"
  template:
    src: "{{ zabbix_extension.name }}/{{ item }}.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart zabbix-agent service
  when: "zabbix_extension.group in group_names"
  loop: "{{ zabbix_extension.configuration_files }}"

- name: "Copy binary files of extension {{ zabbix_extension.name }}"
  copy:
    src: "{{ zabbix_extension.name }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  become: true
  when: "zabbix_extension.group in group_names"
  loop: "{{ zabbix_extension.binary_files }}"
